{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prometheus.fullname" . }}-config
data:
  prometheus.yaml: |-
    global:
      scrape_interval: 5s

    rule_files:
    - /etc/prometheus/alerts/*.yaml

    # Alerting specifies settings related to the Alertmanager
    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            - {{ template "alertmanager.fullname" . }}:{{ .Values.alertmanager.service.port }}
            
    scrape_configs:
    - job_name: endpoints
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      kubernetes_sd_configs:
      - role: endpoints

      relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_service_label_app]
        regex: telliot.*|prometheus|export.*
      - action: replace
        source_labels: [__meta_kubernetes_service_label_app]
        target_label: job
      - action: labeldrop
        regex: __meta_kubernetes_namespace|__meta_kubernetes_pod_node_name|__meta_kubernetes_pod_label_node
{{- end }}