{{- range $index := .Values.telliot.modes }}
{{- $val := dict "mode" $index }}
{{- $modeName := printf "%s-%s" (include "telliot.fullname" $) (include "telliot.modeName" $val) | trunc 63 | trimSuffix "-" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $modeName }}
type: Opaque
data:
  {{- if $.Values.telliot.uniqueConfiguration }}
  {{- $path := printf "%s/%s" "files" ($modeName | lower) }}
  {{- else }}
  {{- $path := "files" }}
  {{- $file := $.Files.Get (printf "%s/%s" $path ".env") | trimSuffix "\n" }}
  {{- range $line := splitList "\n" $file }}
  {{- if and (contains "=" $line) (not (hasPrefix "#" $line)) }}
  {{- $kv := splitList "=" $line }}
  {{- $commentSafeValue := first (splitList "#" (last $kv)) }}
  {{ first $kv }}: {{ b64enc $commentSafeValue }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}