apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telliot-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telliot-db
  labels:
    app: telliot-db
spec:
  serviceName: telliot-db
  replicas: 1
  selector:
    matchLabels:
      app: telliot-db
  template:
    metadata:
      labels:
        app: telliot-db
    spec:
      containers:
      - name: telliot-db
        image: tellor/telliot:latest
        imagePullPolicy: Always
        args: ["dataserver"]
        ports:
        - name: telliot-db
          containerPort: 9090
        volumeMounts:
        - name: configs
          mountPath: "/configs"
        - name: db
          mountPath: "/db"
        env:
        - name: NODE_URL
          valueFrom:
            secretKeyRef:
              name: telliot-db
              key: NODE_URL
        - name: VIXEOD_KEY
          valueFrom:
            secretKeyRef:
              name: telliot-db
              key: VIXEOD_KEY
        - name: CMC_KEY
          valueFrom:
            secretKeyRef:
              name: telliot-db
              key: CMC_KEY
        - name: RAPID_KEY
          valueFrom:
            secretKeyRef:
              name: telliot-db
              key: RAPID_KEY
        - name: ANYBLOCK_KEY
          valueFrom:
            secretKeyRef:
              name: telliot-db
              key: ANYBLOCK_KEY
      volumes:
      - name: configs
        configMap:
          name: telliot-db
      - name: db
        persistentVolumeClaim:
          claimName: telliot-db
---
kind: Service
apiVersion: v1
metadata:
  name: telliot-db
  labels:
    app: telliot-db
spec:
  selector:
    app: telliot-db
  ports:
  - name: telliot-db
    port: 9090
    targetPort: telliot-db
