{{- if .Values.alertmanager.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "alertmanager.fullname" . }}
spec:
  serviceName: {{ template "alertmanager.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "alertmanager.fullname" . }}
  template:
    metadata:
      name: {{ template "alertmanager.fullname" . }}
      labels:
        app: {{ template "alertmanager.fullname" . }}
    spec:
      containers:
      - name: {{ template "alertmanager.fullname" . }}
        image: {{ .Values.alertmanager.container.image }}
        args:
          - "--config.file=/etc/alertmanager/config.yml"
          - "--storage.path=/alertmanager"
        ports:
        - name: http
          containerPort: {{ .Values.alertmanager.container.port }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "alertmanager.fullname" . }}-config
      - name: templates-volume
        configMap:
          name: {{ template "alertmanager.fullname" . }}-templates
{{- end }}