{{- if .Values.alertmanager.enabled }}
{{- if .Values.alertmanager.bot.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "alertmanager.fullname" . }}-bot
spec:
  ports:
  - name: http
    port: {{.Values.alertmanager.bot.service.port }}
    targetPort: {{.Values.alertmanager.bot.container.port }}
  selector:
    app: {{ template "alertmanager.fullname" . }}-bot
{{- end }}
{{- end }}