{{- if .Values.alertmanager.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "alertmanager.fullname" . }}-config
data:
  config.yml: |-
    global:
    templates:
      - "/etc/alertmanager/*.tmpl"
    route:
      receiver: alertmananger-bot
      group_by: ["alertname", "priority"]
      group_wait: 10s
      repeat_interval: 30m

    receivers:
      - name: alertmananger-bot
        webhook_configs:
          - send_resolved: true
            url: "http://{{ template "alertmanager.fullname" . }}-bot:{{ .Values.alertmanager.bot.service.port }}"
{{- end }}