{{- if .Values.alertmanager.enabled }}
{{- if .Values.alertmanager.bot.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "alertmanager.fullname" . }}-bot
type: Opaque
data:
  admin: "{{.Values.alertmanager.bot.telegram.admin}}"
  token: "{{.Values.alertmanager.bot.telegram.token}}"
{{- end }}
{{- end }}